# Site settings
title:       jasonrclark.com
email:       jason@jasonrclark.com
author:      Jason Clark
description: "A simple, beautiful theme for Jekyll that emphasizes content rather than aesthetic fluff."
baseurl:     ""
url:         "http://jasonrclark.com"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
permalink:    pretty
paginate:     3
sass:
  compressed: true
gems:
  - jekyll-sitemap
