var words = [
  ["enseñar", "to teach"],
  ["pared", "wall"],
  ["pizarra", "whiteboard"],
  ["casado", "married"],
  ["cara", "face"],
  ["venir", "to come"],
  ["cartera", "wallet"],
  ["lentillas", "contacts"],
  ["pajina", "page"],
  ["explicar", "to explain"],
  ["lugar", "place"],
  ["hacer", "to do"],
  ["desde cuándo", "how long"],
  ["_verbo_ desde hace __", "I have __ for __ time"],
  ["llegar", "to arrive"],
  ["casi", "almost"],
  ["traducir", "to translate"],
  ["contar", "to tell"],
  ["recordar", "remember"],
  ["ancha", "wide"],
  ["al lado", "next to"],
  ["parecer", "to seem"],
  ["le cuesta/n", "to have trouble with"],
  ["libreta", "notebook"],
  ["cuaderno", "notebook"],
  ["echo de menus", "to miss"],
  ["perder", "to lose"],
  ["volver", "to return"],
  ["decir", "to say"],
  ["olvidar", "to forget"],
  ["pedir", "to ask for"],
];
