var words = [
  ["enseñar", "to teach"],
  ["pared", "wall"],
  ["pizarra", "whiteboard"],
  ["casado", "married"],
  ["cara", "face"],
  ["venir", "to come"],
  ["cartera", "wallet"],
  ["lentillas", "contacts"],
  ["pajina", "page"],
  ["explicar", "to explain"],
  ["lugar", "place"],
  ["hacer", "to do, to make"],
  ["desde cuándo", "how long"],
  ["-verbo- desde hace -tiempo-", "I have -verb- for -length of time-"],
  ["llegar", "to arrive"],
  ["casi", "almost"],
  ["traducir", "to translate"],
  ["contar", "to tell"],
  ["recordar", "remember"],
  ["ancha", "wide"],
  ["al lado", "next to"],
  ["parecer", "to seem"],
  ["le cuesta/n", "to have trouble with"],
  ["libreta", "notebook"],
  ["cuaderno", "notebook"],
  ["echo de menus", "to miss"],
  ["perder", "to lose"],
  ["volver", "to return"],
  ["decir", "to say"],
  ["olvidar", "to forget"],
  ["pedir", "to ask for"],
  ["segundo", "second (time)"],
  ["lejos", "far"],
  ["cordero", "lamb"],
  ["pierna", "leg"],
  ["pie", "foot"],
  ["brazo", "arm"],
  ["dedo", "finger"],
  ["cuerpo", "body"],
  ["estómago", "stomach"],
  ["espalda", "back"],
  ["pecho", "cehst"],
  ["enfermera", "nurse"],
  ["enfermo", "sick"],
  ["encargado", "manager"],
  ["deber", "to owe, must, should, ought to"],
  ["quedar", "to stay, remain"],
  ["dejar", "to leave, abandon, to let, allow"],
  ["seguir", "to follow, continue"],
  ["encontrar", "to find, encounter"],
  ["llamar", "to call, to name"],
  ["pensar", "to think"],
  ["conocer", "to know (people, places)"],
  ["sentir", "to feel, regret"],
  ["tratar", "to treat, handle"],
  ["existir", "to exist"],
  ["recibir", "to receive, to welcome, greet"],
  ["terminar", "to finish, end"],
  ["aparecer", "to appear, show up"],
  ["conseguir", "to get, obtain"],
  ["comenzar", "to begin, start, commence"],
  ["sacar", "to take out, stick out"],
  ["caer", "to fall"],
  ["acabar", "to finish, end"],
  ["traer", "to bring, to get, fetch, to carry"],
  ["suponer", "to suppose"],
  ["reconocer", "to recognize"],
  ["alcanzar", "to reach, catch up"],
  ["ofrecer", "to offer"],
  ["levantar", "to raise, to lift"],
];
