var words = [
  ["pared", "wall"],
  ["pizarra", "whiteboard"],
  ["venir", "to come"],
  ["cartera", "wallet"],
  ["lugar", "place"],
  ["desde cuándo", "how long"],
  ["-verbo- desde hace -tiempo-", "I have -verb- since -length of time-"],
  ["llegar", "to arrive"],
  ["casi", "almost"],
  ["traducir", "to translate"],
  ["contar", "to tell"],
  ["recordar", "remember"],
  ["parecer", "to seem"],
  ["le cuesta/n", "to have trouble with"],
  ["libreta, cuaderno", "notebook"],
  ["echo de menus", "to miss"],
  ["perder", "to lose"],
  ["volver", "to return"],
  ["decir", "to say"],
  ["olvidar", "to forget"],
  ["pedir", "to ask for"],
  ["segundo", "second (time)"],
  ["lejos", "far"],
  ["cordero", "lamb"],
  ["pierna", "leg"],
  ["brazo", "arm"],
  ["cuerpo", "body"],
  ["espalda", "back"],
  ["pecho", "chest"],
  ["encargado", "manager"],
  ["deber", "to owe, must, should, ought to"],
  ["quedar", "to stay, remain"],
  ["dejar", "to leave, abandon, to let, allow"],
  ["seguir", "to follow, continue"],
  ["encontrar", "to find, encounter"],
  ["llamar", "to call, to name"],
  ["pensar", "to think"],
  ["conocer", "to know (people, places)"],
  ["sentir", "to feel, regret"],
  ["tratar", "to treat, handle"],
  ["recibir", "to receive, to welcome, greet"],
  ["aparecer", "to appear, show up"],
  ["conseguir", "to get, obtain"],
  ["comenzar", "to begin, start, commence"],
  ["caer", "to fall"],
  ["traer", "to bring, to get, fetch, to carry"],
  ["suponer", "to suppose"],
  ["reconocer", "to recognize"],
  ["alcanzar", "to reach, catch up"],
  ["ofrecer", "to offer"],
  ["navigador", "browser"],
  ["mitad", "half"],
  ["inicio", "half"],
  ["excusa", "excuse"],
  ["cantidad", "quantity"],
  ["durante", "during"],
  ["césped", "grass"],
  ["luego, entonces", "then"],
  ["nacer", "to be born"],
  ["util", "useful"],
  ["corregir", "edit"],
  ["castigar", "to punish"],
  ["pisar", "to step on"],
  ["detener, parar", "to stop"],
  ["acá", "over here"],
  ["allí", "there"],
  ["allá", "over there"],
  ["lavar", "to wash"],
  ["levantarse", "to get up"],
  ["despertar", "to wake"],
  ["bañera", "bath"],
  ["nevera", "fridge"],
  ["lavabo", "sink"],
  ["esos/esas", "those"],
  ["ese/esa", "that"],
  ["esto/esta", "this"],
  ["driveway", "entrada de coches"],
  ["levantar", "to raise, to lift"],
];
