var words = [
  ["abogado", "lawyer"],
  ["acabar", "to finish"],
  ["acostarse", "to lie down"],
  ["acá", "over here"],
  ["adivinar", "to guess"],
  ["alcanzar", "to reach, catch up"],
  ["alegre", "happy, cheerful"],
  ["allá", "over there"],
  ["allí", "there"],
  ["anillo", "ring"],
  ["aparecer", "to appear, show up"],
  ["armario", "wardrobe"],
  ["bañador", "swimsuit"],
  ["bañera", "bath"],
  ["broma", "joke"],
  ["cariñosa", "affectionate"],
  ["casi", "almost"],
  ["casilla", "box"],
  ["componer", "to compose"],
  ["conseguir", "to get, obtain"],
  ["contar", "to tell"],
  ["cotidiana", "daily"],
  ["deber", "to owe, must, should, ought to"],
  ["dejar", "to leave, abandon, to let, allow"],
  ["delantel de cocina", "apron"],
  ["delgado", "thin"],
  ["descansar", "to rest"],
  ["descubrir", "to discover"],
  ["despertar", "to wake"],
  ["detener, parar", "to stop"],
  ["echo de menus", "to miss"],
  ["edad", "age"],
  ["el campo", "countryside"],
  ["encajar", "to fit"],
  ["encargado", "manager"],
  ["encontrar", "to find, encounter"],
  ["ese/esa", "that"],
  ["esos/esas", "those"],
  ["esto/esta", "this"],
  ["fuego", "fire"],
  ["gira", "tour"],
  ["gordo", "fat"],
  ["hace", "ago"],
  ["huelga", "strike"],
  ["jubilarse", "to retire"],
  ["lanzar", "to throw"],
  ["lavabo", "sink"],
  ["lavar", "to wash"],
  ["le cuesta/n", "to have trouble with"],
  ["lejos", "far"],
  ["levantar", "to raise, to lift"],
  ["levantarse", "to get up"],
  ["liso", "smooth"],
  ["llamar", "to call, to name"],
  ["llegar", "to arrive"],
  ["llevarse bien/mal", "to get along with/not"],
  ["madura", "mature"],
  ["medir", "to measure"],
  ["nariz", "nose"],
  ["nevera", "fridge"],
  ["obtener", "to get"],
  ["ofrecer", "to offer"],
  ["paracerse a", "to look like"],
  ["parecer", "to seem"],
  ["pareja", "couple"],
  ["pedir", "to ask for"],
  ["pendientes", "earrings"],
  ["perder", "to lose"],
  ["perfil", "profile"],
  ["perilla", "goatee"],
  ["pesar", "to weigh"],
  ["pisar", "to step on"],
  ["prenda", "item of clothing"],
  ["pulsera", "braclet"],
  ["punto clave", "key point"],
  ["quedar", "to meet"],
  ["quedarse", "to stay, remain"],
  ["raíz", "root"],
  ["recibir", "to receive, to welcome, greet"],
  ["reconocer", "to recognize"],
  ["rizado", "curly"],
  ["seguir", "to follow, continue"],
  ["sentir", "to feel, regret"],
  ["siglo", "century"],
  ["sobrino", "nephew"],
  ["soltero", "single"],
  ["sonrisa", "smile"],
  ["soprender", "to surprise"],
  ["superar", "to overcome"],
  ["suponer", "to suppose"],
  ["teñirse", "to dye"],
  ["todavía", "still"],
  ["todo recto", "straight"],
  ["tratar", "to treat, handle"],
];
